src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être supérieure à la date d'aujourd'hui", groups={"Front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être supérieure à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist()
    {
        if (empty($this->created_at)) {
            $this->created_at = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->updated_at = new \DateTime();
    }

    /**
     * @return bool
     */
    public function isBookableDates(): bool
    {
        $days             = $this->getDays();
        $notAvailableDays = $this->getAd()->getNotAvailableDays();

        $formatDay = function($day) {
            return $day->format('Y-m-d');
        };

        $days             = array_map($formatDay,$days);
        $notAvailableDays = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (in_array($day, $notAvailableDays)) {
                return false;
            }
        }

        return true;
    }

    /**
     * @return array [Datetime]
     */
    public function getDays(): array
    {
        $resultats = range($this->getStartDate()->getTimestamp(), $this->getEndDate()->getTimestamp(), (24 * 60 * 60));

        return array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultats);
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);

        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File as FileFile;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email", message="Cette adresse mail existe déjà")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Prénom obligatoire")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Nom obligatoire")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Cette adresse mail n'est pas valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @var FileFile|null
     * @Assert\Image(mimeTypes={"image/jpeg", "image/png"}, mimeTypesMessage="Seul les formats JPEG et PNG sont autorisés", maxSize="2M", maxSizeMessage="Taille max 2M")
     * @Vich\UploadableField(mapping="users_image", fileNameProperty="picture")
     */
    private $pictureFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Confirmation mot de passe incorrecte")
     */
    private $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max="255", minMessage="L'introduction doit faire au moins 10 caractères", maxMessage="L'introduction doit faire au maximum 255 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="La description doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->ads        = new ArrayCollection();
        $this->created_at = new \DateTime();
        $this->userRoles  = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->updated_at = new \DateTime();
    }

    public function getFullName(): string
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify    = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return FileFile|null
     */
    public function getPictureFile(): ?FileFile
    {
        return $this->pictureFile;
    }

    /**
     * @param FileFile|null $pictureFile
     * @return User
     * @throws \Exception
     */
    public function setPictureFile(?FileFile $pictureFile): User
    {
        $this->pictureFile = $pictureFile;
        $now          = (new \DateTime())->format('Y-m-d H:i:s');
        $creationDate = $this->getCreatedAt()->format('Y-m-d H:i:s');

        if ($this->pictureFile instanceof UploadedFile && $creationDate != $now) {
            $this->updated_at = $now;
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPasswordConfirm()
    {
        return $this->passwordConfirm;
    }

    /**
     * @param mixed $passwordConfirm
     * @return User
     */
    public function setPasswordConfirm($passwordConfirm)
    {
        $this->passwordConfirm = $passwordConfirm;
        return $this;
    }

    /**
     * @return string[]
     */
    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    /**
     * @return string|null
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * @return string|void|null
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     *
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class BookingController extends AbstractController
{

    /**
     * @var EntityManagerInterface
     */
    protected EntityManagerInterface $manager;

    public function __construct(EntityManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    /**
     * @param Ad      $ad
     * @param Request $request
     * @return Response
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request): Response
    {
        $booking = new Booking();
        $form    = $this->createForm(BookingType::class, $booking, [
//            'validation_groups' => ["Default", "Front"] // Fait directement dans le BookingType
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user)->setAd($ad);

            if (!$booking->isBookableDates()) {
                $this->addFlash('warning', "Les dates choisies ne sont pas disponibles");
            } else {
                $this->manager->persist($booking);
                $this->manager->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'withAlert' => true]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad'   => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * @param Booking $booking
     * @param int     $id
     * @param Request $request
     * @return Response
     */
    public function show(Booking $booking, int $id, Request $request): Response
    {
        if ($booking->getId() !== $id) {
            return $this->redirectToRoute('home', [], 301);
        }

        $comment = new Comment();
        $form    = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $this->manager->persist($comment);
            $this->manager->flush();

            $this->addFlash('success', 'Votre commentaire a bien été enregistré !');
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form'    => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('datepickercss') }}
{% endblock %}

{% block title %}Réserver l'annonce : {{ ad.title }}{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="h2 my-5 text-center">Réserver pour l'annonce {{ ad.title }}</h1>
        <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong></p>

        {{ form_start(form) }}
        <div class="alert alert-light">
            <h2 class="h4 my-5 text-center">Commencez par indiquer vos dates</h2>
            <div id="bookingJourney" class="row"
                 data-booking-notavailabledays="{{ ad.notAvailableDays | map((elem) => elem | date('d/m/Y')) | json_encode }}"
                 data-booking-price="{{ ad.price }}"
            >
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>

            <h3 class="mt-3">Montant du séjour : <span id="amount">...</span>€</h3>
            <span id="days">0</span> jour(s) à {{ ad.price | number_format(2, ',', ' ') }}€ par nuit

            <hr>
            {{ form_row(form.comment) }}
        </div>

        <button type="submit" class="btn btn-success">Réserver</button>

        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('datepickerjs') }}
    {{ encore_entry_script_tags('booking') }}
{% endblock %}

templates/booking/bookingList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos réservations{% endblock %}

{% block body %}
    <div class="container">
        <div class="alert alert-info mt-5">
            <h1>Mes réservations</h1>
        </div>
        {% for booking in app.user.bookings %}
            {% set ad = booking.ad %}
            <div class="row my-3">
                <div class="col-md-4 align-items-stretch">
                    <img class="img-fluid" src="{{ vich_uploader_asset(ad, 'coverFile') }}"
                         alt="annonce-{{ ad.title }}">

                    <div class="mt-3">
                        {% set comment = ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <strong>Note donnée : </strong>{% include 'partials/rating.html.twig' with { 'rating': comment.rating } %}
                        {% elseif date() > date(booking.endDate) %}
                            Vous n'avez pas encore donné de note.
                            <a href="{{ path('booking_show', { "id": booking.id }) }}#comment">Je mets un avis</a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-8 align-items-stretch">
                    <h2 class="h4">{{ ad.title }}</h2>
                    <p>Réservation <strong>n°{{ booking.id }}</strong>
                    Du {{ booking.startDate | date('d/m/Y') }} au {{ booking.endDate | date('d/m/Y') }}
                    ({{ booking.amount }}€)
                    </p>
                    <div>
                        <a href="{{ path('booking_show', {"id": booking.id}) }}" class="btn btn-info">Plus
                            d'informations</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{ booking.id }}{% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h1 class="text-center mt-4 mb-5">Votre réservation {{ booking.id }}</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
               <p>Votre réservation auprès de {{ author.fullName }} pour l'annonce {{ ad.title }} à bien été prise en compte</p>
            </div>
        {% endif %}

        <div class="row">
            <div class="col-6 align-items-stretch">
                <div class="alert alert-light">
                    <h2 class="text-center mb-4">Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d-m-Y') }}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d-m-Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{ booking.amount }}€</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>
                    <hr>
                    <h2 class="alert-heading text-center mb-4">Votre hôte</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            <img class="avatar avatar-medium" src="{{ vich_uploader_asset(author, 'pictureFile') }}" alt="avatar-{{ author.fullName }}">
                        </div>
                        <div class="col-9">
                            <h3>
                                <a href="{{ path('user_show', { "slug": author.slug }) }}" class="linkText">{{ author.fullname }}</a>
                            </h3>
                            <span class="badge badge-primary">{{ author.ads | length }} annonce(s)</span>
                        </div>
                    </div>
                    {{ author.description | raw }}
                    <div class="text-center mb-2">
                        <a href="{{ path('user_show', { "slug": author.slug }) }}" class="linkText btn btn-primary">Plus d'infos sur {{ author.firstname }}</a>
                    </div>
                </div>
                <div class="alert alert-light" id="comment">
                    <h2 class="alert-heading">Votre avis compte !</h2>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note :</strong>{% include 'partials/rating.html.twig' with { "rating": comment.rating } %}
                        {% else %}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Confirmer</button>
                            </div>
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pouvez pas encore noter cette annonce</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-6 d-flex align-items-stretch">
                <div class="alert alert-light">
                    <h2 class="alert-heading text-center mb-4">Votre hébergement</h2>
                    <h4>
                        <a href="{{ path('ads_show', { "slug": ad.slug, "id": ad.id }) }}" class="linkText">{{ ad.title }}</a>
                    </h4>
                    <img src="{{ vich_uploader_asset(ad, 'coverFile') }}" alt="{{ ad.title }}" class="img-fluid mb-3 mt-3">

                    {{ ad.content | raw }}

                    <div class="text-center mb-2">
                        <a href="{{ path('ads_show', { "slug": ad.slug, "id": ad.id }) }}" class="btn btn-primary linkText">Plus d'informations</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}