src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File as FileFile;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 * @UniqueEntity("title", message="une autre annonce possède déjà ce titre")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10", max="255", minMessage="Minimum 10 caratères", maxMessage="Maximum 255 caratères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max="255", maxMessage="Le slug doit faire au maximum 255 caratères")
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="10", max="255", minMessage="Minimum 10 caratères", maxMessage="Maximum 255 caratères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="100", minMessage="Minimum 100 caratères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @var FileFile
     * @Assert\Image(mimeTypes={"image/jpeg", "image/png"}, mimeTypesMessage="Seul les formats JPEG et PNG sont autorisés", maxSize="2M", maxSizeMessage="Taille max 2M")
     * @Vich\UploadableField(mapping="ads_image", fileNameProperty="coverImage")
     */
    private $coverFile;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images     = new ArrayCollection();
        $this->created_at = new \DateTime();
        $this->bookings   = new ArrayCollection();
        $this->comments   = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify    = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->updated_at = new \DateTime();
    }

    /**
     * @return float|int
     */
    public function getAvgRatings()
    {
        $sumOfRatings = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        return $sumOfRatings > 0 ? ($sumOfRatings / count($this->comments)) : 0;
    }

    /**
     * @param User $author
     * @return mixed|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) {
                return $comment;
            }
        }

        return null;
    }

    /**
     * @return array [Datetime]
     */
    public function getNotAvailableDays(): array
    {
        $notAvailableDays = [];
        foreach ($this->bookings as $booking) {
            $resultat = range($booking->getStartDate()->getTimestamp(), $booking->getEndDate()->getTimestamp(), (24 * 60 * 60));

            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(?string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return FileFile
     */
    public function getCoverFile(): ?FileFile
    {
        return $this->coverFile;
    }

    /**
     * @param FileFile $coverFile
     * @return Ad
     * @throws \Exception
     */
    public function setCoverFile(FileFile $coverFile): Ad
    {
        $this->coverFile = $coverFile;

        if ($this->coverFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }


}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class, $this->getConfig('Titre', "Entrez votre titre"))
                ->add('slug', TextType::class, $this->getConfig('Chaîne URL', 'Titre de la page dans la barre d\'adresse (automatique)', ['required' => false]))
                ->add('coverFile', FileType::class, $this->getConfig('Charger une image', 'Une belle image pour votre annonce', ['required' => false]))
                ->add('introduction', TextType::class, $this->getConfig('Introduction', 'Donnez description globale de votre annonce'))
                ->add('content', TextareaType::class, $this->getConfig('Détaillez votre annonce', 'Description détaillée'))
                ->add('rooms', IntegerType::class, $this->getConfig('Nombre de chambre', 'Chambre(s) disponible(s)'))
                ->add('price', MoneyType::class, $this->getConfig('Prix par nuit', 'Prix par nuit'))
                ->add('images', CollectionType::class, ['entry_type' => ImageType::class, 'allow_add' => true, 'allow_delete' => true, 'allow_file_upload' => true]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Ad::class,
            ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\AdType;
use App\Repository\AdRepository;
use App\Service\Pagination;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class AdController extends AbstractController
{
    /**
     * @var AdRepository
     */
    protected $repository;

    /**
     * @var EntityManagerInterface
     */
    protected $manager;

    /**
     * @var Pagination
     */
    protected $pagination;

    public function __construct(AdRepository $repository, EntityManagerInterface $manager, Pagination $pagination)
    {
        $this->repository = $repository;
        $this->manager    = $manager; //Plus pour ajout/suppression en base
        $this->pagination = $pagination;
    }

    /**
     * @param $page
     * @return Response
     */
    public function index(int $page)
    {
        $this->pagination->setEntityClass(Ad::class)->setCurrentPage($page)->setLimit(12);

        return $this->render('ad/index.html.twig', [
            'pagination' => $this->pagination
        ]);
    }

    /**
     * @param Ad     $ad
     * @param string $slug
     * @param int    $id
     * @return RedirectResponse|Response
     */
    public function show(Ad $ad, string $slug, int $id)
    {
        if ($ad->getSlug() !== $slug || $ad->getId() !== $id) {
            return $this->redirectToRoute('ads_show', [
                'id'   => $ad->getId(),
                'slug' => $ad->getSlug()
            ], 301);
        }

//        $ad = $this->repository->findOneBySlug($slug); // Ne sert plus car on a déjà la bonne entité! (Cf: ParamConverter)

        return $this->render('ad/show.html.twig', ['ad' => $ad]);
    }

    /**
     * @IsGranted("ROLE_USER")
     *
     * @param Request $request
     * @return Response
     */
    public function create(Request $request)
    {
        $ad   = new Ad();
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $this->manager->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $this->manager->persist($ad);
            $this->manager->flush();

            $this->addFlash(
                'success', "Annonce <strong>{$ad->getTitle()}</strong> enregistrée !"
            );

            return $this->redirectToRoute('ads_show', [
                'id'   => $ad->getId(),
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous n'êtes pas le propriétaire de cette annonce.")
     *
     * @param Request $request
     * @param Ad      $ad
     * @return Response
     */
    public function edit(Request $request, Ad $ad)
    {
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $this->manager->persist($image);
            }

            $this->manager->persist($ad);
            $this->manager->flush();

            $this->addFlash(
                'success', "Annonce <strong>{$ad->getTitle()}</strong>Modifications enregistrée !"
            );

            return $this->redirectToRoute('ads_show', [
                'id'   => $ad->getId(),
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()")
     *
     * @param Request $request
     * @param Ad      $ad
     * @return Response
     */
    public function delete(Request $request, Ad $ad): Response
    {
        if ($this->isCsrfTokenValid('delete' . $ad->getSlug(), $request->get('_token'))) {
            $this->manager->remove($ad);
            $this->manager->flush();

            $this->addFlash(
                'success', "Annonce <strong>{$ad->getTitle()}</strong> supprimée!");

            return $this->redirectToRoute('ads');
        }

        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }
}

templates/ad/_ad.html.twig
{% set pathToAd = path('ads_show', {'slug': ad.slug, 'id': ad.id}) %}
<div class="col-md-4 d-flex align-items-stretch">
    <div class="ads card bg-white mb-3 w-100">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price }}€ / nuit</strong>
            <br>
            {% if ad.comments | length %}
                {% include 'partials/rating.html.twig' with { 'rating': ad.avgRatings } %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>

        <a href="{{ pathToAd }}">
            {% if ad.coverImage %}
                <img src="{{ vich_uploader_asset(ad, 'coverFile')}}" class="m-0" style="height: 200px; width: 100%; display: block;" alt="cover image">
            {% else %}
                <img src=" {{ asset('/images/empty.jpeg') }}" class="d-block w-100" alt="default">
            {% endif %}
        </a>

        <div class="card-body p-0 w-75 align-self-center align-text-bottom mt-2">
            <a href="{{ pathToAd }}">
                <strong class="h6 card-title text-center m-2">{{ ad.title }}</strong>
            </a>
            <p class="card-text align-text-bottom">{{ ad.introduction }}</p>
        </div>
        <div class="text-center my-2">
            <a href="{{ pathToAd }}" class="btn btn-secondary">En savoir plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {"id": ad.id, "slug": ad.slug }) }}" class="btn btn-info">Modifier</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>Ajouter des images supplémentaires</p>
    {{ form_widget(form) }}

{#    <input type="hidden" id="widgets-counter" value="0">#}

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary"><i class="fas fa-plus"></i> Ajouter une image</button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row gallery-element">
            <div class="col-10">
                <div class="row">
                    <div class="col-8">
                        {{ form_widget(form.caption) }}
                    </div>
                    <div class="col-4">
                        {{ form_widget(form.urlFile) }}

{#                        {{ dump(form) }}#}

{#                        {% if form.vars.data.imageFilename %}#}
{#                            <img src="{{ asset(articleForm.vars.data.imagePath) }}" height="100">#}
{#                        {% endif %}#}

                        {#{{ form.url.vars.value }}#}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition de l'annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Edition de l'annonce</h1>

        {{ form_start(form) }}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Informations générales</h2>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.slug) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.rooms) }}
                </div>
                <div class="alert alert-light">
                    <h2>Détails de l'annonce</h2>
                    <hr>
                    {{ form_row(form.introduction) }}
                    {{ form_row(form.content) }}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light clearfix">
                    <h2>Images</h2>
                    <hr>
                    {{ form_row(form.coverFile) }}
                    {{ form_row(form.images) }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-5"><i class="fas fa-check"></i> Sauvegarder</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('ad') }}
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="h1 text-center my-5">Les annonces de nos hôtes</h1>
        <div class="row">
            {% for ad in pagination.data %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>
    {{ pagination.display }}
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
    <div class="container mb-5">
        <h1 class="my-5 text-center">Créer une nouvelle annonce</h1>
        {{ form_start(form) }}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Informations générales</h2>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.slug) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.rooms) }}
                </div>
                <div class="alert alert-light">
                    <h2>Détails de l'annonce</h2>
                    <hr>
                    {{ form_row(form.introduction) }}
                    {{ form_row(form.content) }}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light clearfix">
                    <h2>Images</h2>
                    <hr>
                    {{ form_row(form.coverFile) }}
                    {{ form_row(form.images) }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2"><i class="fas fa-check"></i> Sauvegarder</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
{#    <script src="{{ asset('js/ad.js') }}"></script>#}
    {{ encore_entry_script_tags('ad') }}
{% endblock %}

{#{% block form_row %}#}
{#    {{ form_label(form) }}#}
{#    {{ form_widget(form) }}#}
{#{% endblock %}#}

{#{% block text_widget %}#}
{#    <input type="text" name="{{ full_name }}" id="{{ id }}" class="form-control">#}
{#{% endblock %}#}

{#{% block url_widget %}#}
{#    #}
{#{% endblock %}#}

{#{% block textarea_widget %}#}
{#    #}
{#{% endblock %}#}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}
    <div class="annonces-title" style="background-image:
    {% if ad.coverImage %}
        url({{ vich_uploader_asset(ad, 'coverFile')}})"
    {% else %}
        {{ asset('/images/empty.jpeg') }}"
    {% endif %}>
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres </strong>pour {{ ad.price }}€ par nuit
            </p>
            <a href="{{ path('booking_create', { "id": ad.id, "slug": ad.slug }) }}" class="btn btn-primary">Réserver</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', { "id": ad.id, "slug": ad.slug }) }}" class="btn btn-info">Modifier</a>
                <form method="post" action="{{ path('ads_delete', { "id": ad.id, "slug": ad.slug }) }}" style="display: inline-block;" onsubmit="return confirm(`Confirmez-vous la suppression de l'annonce {{ ad.title }} ?`)">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ad.slug) }}">
                    <button class="btn btn-danger">Supprimer</button>
                </form>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-8 mb-3">
                {{ ad.content | raw }}

                <div id="carouselExampleIndicators" class="carousel slide mt-5" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images  %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{% endif %} }}">
                            {% if image.url %}
                                <img src="{{ vich_uploader_asset(image, 'urlFile')}}" class="d-block w-100" alt="{{ image.caption }}">
                            {% else %}
                                <img src=" {{ asset('/images/empty.jpeg') }}" class="d-block w-100" alt="default">
                            {% endif %}

                            <div class="carousel-caption d-none d-md-block">
                                <p>{{ image.caption }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {% if ad.comments | length > 0 %}
                    <h2 class="mt-5">Commentaires de nos utilisateurs</h2>

                    <div class="alert alert-info">
                        <h3 class="h4 alert-heading">
                            <div class="row align-items-center">
                                <div class="col text-center">
                                    Note globale :
                                </div>
                                <div class="col">
                                    {% include 'partials/rating.html.twig' with { 'rating': ad.avgRatings } %}
                                    <br><small>Calculée sur {{ ad.comments | length }} avis</small>
                                </div>
                            </div>
                        </h3>
                    </div>

                    {% for comment in  ad.comments %}
                        <div class="bg-light rounded mb-3 p-3">
                            <strong>{{ comment.author.fullName }}</strong>
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note donnée par {{ comment.author.firstName }}</strong> :
                            {% include 'partials/rating.html.twig' with { 'rating': comment.rating } %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h2>Cette annonce n'a pas encore reçu de commentaire</h2>
                {% endif %}
            </div>
            <div class="col ml-5">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-3">
                        <a href="{{ path('user_show', { 'slug': a.slug }) }}">
                            <img src="{{ vich_uploader_asset(a, 'pictureFile')}}" class="avatar avatar-medium d-block w-100" alt="avatar-{{ a.fullName }}">
                        </a>
                    </div>
                    <div class="col-9">
                        <a class="linkText" href="{{ path('user_show', { 'slug': a.slug }) }}">
                            <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge badge-primary">{{ a.ads | length}} annonces</span>
                    </div>
                </div>
                <br>
                {{ a.description | raw }}
            </div>
        </div>
    </div>
{% endblock %}